# Операції над масивами
> хоча базово всі дані інтерпретуються як масиви, можливо працювавти з двовимірними масивами як алгебраїчними матрицями.

In [28]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np

> згенеруємо декілька масивів різними способами та виконаємо базові математичні операції.

In [29]:
import numpy as np

# Створення матриці eye
eye_matrix = np.eye(5)  # Матриця 5x5 із одиницями на головній діагоналі
print("Матриця eye:")
print(eye_matrix)

# Порівняння елементів матриці на наявність 1
comparison = eye_matrix == 1
print("\nПорівняння на наявність 1:")
print(comparison)

# Створення матриці ones
ones_matrix = np.ones((5, 5))  # Матриця 5x5, заповнена одиницями
print("\nМатриця ones:")
print(ones_matrix)

# Віднімання матриці eye від матриці ones
result_matrix = ones_matrix - eye_matrix
print("\nРезультат віднімання (матриця з нулями на центральній діагоналі):")
print(result_matrix)


Матриця eye:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Порівняння на наявність 1:
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]

Матриця ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Результат віднімання (матриця з нулями на центральній діагоналі):
[[0. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 0.]]


# Множення матриць
>  якщо маси яно не задати як матрицю, тоді операції будуть виконуавтись до кожного елемента.

In [30]:
import numpy as np

A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

print(f"Маємо два масиви:\n{A} \n{B}")

R = A * B
print(f"Тут виконується поелементне множення:\n{R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n{R}")

MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n{R}")


Маємо два масиви:
[[1 2 3]
 [2 2 2]
 [3 3 3]] 
[[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Вирівнювання розмірностей
> broadcasting - механізм який дозволяє вирівняти розмірність масивів для того щоб здійснити операцію над кожним його елементом. Масиви повинні бути співрозмірні, або один з вимірівв має бути 1 (рядок або стопець).

In [31]:
import numpy as np

A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

print(f"Маємо два масиви:\n{A} \n{B}")

R = A * B
print(f"Тут виконується поелементне множення:\n{R}")

R = np.dot(A, B)
print(f"Тут, масиви перемножуються як матриці:\n{R}")

MA = np.asmatrix(A)
MB = np.asmatrix(B)

R = MA * MB
print(f"Тут масиви перетворені на матриці і далі перемножуються:\n{R}")


Маємо два масиви:
[[1 2 3]
 [2 2 2]
 [3 3 3]] 
[[ 3  2  1]
 [ 1  2  3]
 [-1 -2 -3]]
Тут виконується поелементне множення:
[[ 3  4  3]
 [ 2  4  6]
 [-3 -6 -9]]
Тут, масиви перемножуються як матриці:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Тут масиви перетворені на матриці і далі перемножуються:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]


# Конкатенація, повторення та зміна форми (shape)
> конкатенація (`concatenate`) - процес зчеплення двох і більше елементів (рядків, стовпців), у нашому випадку масивів які мають однакову форму shape;

> повторення (`tile`) - процес побудови масива шляхом повторення заданого елемента;

> зміна форми (`reshape`) або розмірності масива за умови що сумарна розмірність залишиться незмінною;

In [32]:
import numpy as np

array1 = np.arange(12).reshape(3, 4) 
print("Масив array1:\n", array1)

concat_result = np.concatenate((array1, array1), axis=0)  
print("\nКонкатенація по рядках:\n", concat_result)

repeated_result = np.tile(array1, (2, 1)) 
print("\nПовторення масиву:\n", repeated_result)

array2 = np.arange(6).reshape(2, 3) 
print("\nМасив array2:\n", array2)

try:
    concat_fail = np.concatenate((array1, array2), axis=0)
except ValueError as e:
    print("\nПомилка конкатенації (не збігаються розміри):", e)

array2 = np.arange(12).reshape(4, 3)
print("\nМасив array2 після додавання елементів:\n", array2)

array2_padded = np.pad(array2, ((0, 0), (0, 1)), mode='constant', constant_values=0)
print("\narray2 після додавання стовпця:\n", array2_padded)

array2_resized = np.resize(array2, (3, 4))
print("\narray2 після зміни розміру до 3x4:\n", array2_resized)

concat_success = np.concatenate((array1, array2_resized), axis=0)
print("\nУспішна конкатенація після зміни розміру array2:\n", concat_success)

array3 = np.arange(12)

print("\nМожливі комбінації reshape для масиву з 12 елементів:")
shapes = [(1, 12), (2, 6), (3, 4), (4, 3), (6, 2), (12, 1)]
for shape in shapes:
    reshaped_array = array3.reshape(shape)
    print(f"Розмірність {shape}:\n", reshaped_array)


Масив array1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Конкатенація по рядках:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Повторення масиву:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Масив array2:
 [[0 1 2]
 [3 4 5]]

Помилка конкатенації (не збігаються розміри): all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

Масив array2 після додавання елементів:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

array2 після додавання стовпця:
 [[ 0  1  2  0]
 [ 3  4  5  0]
 [ 6  7  8  0]
 [ 9 10 11  0]]

array2 після зміни розміру до 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Успішна конкатенація після зміни розміру array2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Можливі комбінації reshape для масиву з 

# Трансформації масивів
> масии можуть бути трансформовані багатьма способами зміщюючи позиції рядкі або стопців;

> транспонація - заміна рядкі на стопці;

> функції `size` та `shape` - дозволяють визначити кількість елементів 

In [33]:
import numpy as np

O = np.arange(6).reshape(3, 2)
O_r = O.reshape((2, 3)) 
O_f = O.flatten()
O_t = O.transpose() 
O_fl = np.flip(O) 
O_fa = np.flip(O, axis=1)  

print(f"""{O}
Змінити розмірність shape {O.shape} на {O_r.shape} при цьому розмір size {O.size} = {O_r.size} та ndim {np.ndim(O)} = {np.ndim(O_r)}:
{O_r}
Також можна перетворити {np.ndim(O)}-х вимірний масив розмірністю {O.shape} на рядок:
{O_f} 
з розмірністю {O_f.shape} при цьому size = {O_f.size} та ndim стане {np.ndim(O_f)}-х вимірним 
Або транспонувати масив щоб він став {O_t.shape} але зверніть увагу на елементи:
{O_t}
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
{O_fl}
Або обернути лише елементи в кожному рядку (або стовпці):
{O_fa}
""")
    
vector = np.arange(12)
print(f"Вектор: {vector}\nРозмірність: {vector.shape}, size: {vector.size}, ndim: {np.ndim(vector)}")

matrix = vector.reshape(3, 4)
print(f"\nМатриця 3x4:\n{matrix}")
    
transposed_matrix = matrix.transpose()
print(f"\nТранспонована матриця:\n{transposed_matrix}")
    
flipped_matrix = np.flip(matrix)
print(f"\nОбертання матриці:\n{flipped_matrix}")
    
flattened_matrix = flipped_matrix.flatten()
print(f"\nПеретворена векторна форма:\n{flattened_matrix}")


[[0 1]
 [2 3]
 [4 5]]
Змінити розмірність shape (3, 2) на (2, 3) при цьому розмір size 6 = 6 та ndim 2 = 2:
[[0 1 2]
 [3 4 5]]
Також можна перетворити 2-х вимірний масив розмірністю (3, 2) на рядок:
[0 1 2 3 4 5] 
з розмірністю (6,) при цьому size = 6 та ndim стане 1-х вимірним 
Або транспонувати масив щоб він став (2, 3) але зверніть увагу на елементи:
[[0 2 4]
 [1 3 5]]
Можна обернути масив (обертаємо по стовпцях і рядках одночасно): 
[[5 4]
 [3 2]
 [1 0]]
Або обернути лише елементи в кожному рядку (або стовпці):
[[1 0]
 [3 2]
 [5 4]]

Вектор: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Розмірність: (12,), size: 12, ndim: 1

Матриця 3x4:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Транспонована матриця:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Обертання матриці:
[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]

Перетворена векторна форма:
[11 10  9  8  7  6  5  4  3  2  1  0]
